### ISSUE TITLE
Scaling Problem X Y on Zonestar Z8PM4Pro V2 ?

### ISSUE THREAD

**Issue by nicclift** [ZONESTAR3D/Z8P#1]
My printer has started trying to get way beyond the limits on the X and Y axes, and when it then starts to print, it does so over the right hand edge of the table, as if it were trying to work on a very much larger table. 

I have tried returning to defaults Control/Restore Defaults but no change. I have also tried reinstalling V2.3.2 Firmware. No change

Any suggestions please?

**Comment by ZONESTAR3D** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi,
        Your kit should be a Z8PM4Pro-MK2, please use it firmware for MK2.
    
        https://github.com/ZONESTAR3D/Firmware/tree/master/Z8/Z8P/Z8PM4-MK2 
        
    I attached it too.
    
     
    
        
                    HallyCTOShenZhen ZONSTAR INNV. Tech. Co., ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        3/9/2023 08:34
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [ZONESTAR3D/Z8P] Scaling Problem X Y on Zonestar Z8PM4Pro V2 ? (Issue #1)
        
      
    
  
  
My printer has started trying to get way beyond the limits on the X and Y axes, and when it then starts to print, it does so over the right hand edge of the table, as if it were trying to work on a very much larger table.
I have tried returning to defaults Control/Restore Defaults but no change. I have also tried reinstalling V2.3.2 Firmware. No change
Any suggestions please?

**Comment by ZONESTAR3D** [comment]
Hi,
Your kit should be a Z8PM4Pro-MK2, please use the firmware for MK2.
https://github.com/ZONESTAR3D/Firmware/tree/master/Z8/Z8P/Z8PM4-MK2

**Comment by nicclift** [comment]
Thank you! On 9 Mar 2023, at 21:13, ZONESTAR 3D Printer ***@***.***> wrote:﻿




    







    font{

        line-height: 1.6;

    }

    ul,ol{

        padding-left: 20px;

        list-style-position: inside;

    }





    
    
        Hi,
        Your kit should be a Z8PM4Pro-MK2, please use it firmware for MK2.
    
        https://github.com/ZONESTAR3D/Firmware/tree/master/Z8/Z8P/Z8PM4-MK2 
        
    I attached it too.
    
     
    
        
                    HallyCTOShenZhen ZONSTAR INNV. Tech. Co., ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        3/9/2023 08:34
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [ZONESTAR3D/Z8P] Scaling Problem X Y on Zonestar Z8PM4Pro V2 ? (Issue #1)
        
      
    
  
  
My printer has started trying to get way beyond the limits on the X and Y axes, and when it then starts to print, it does so over the right hand edge of the table, as if it were trying to work on a very much larger table.
I have tried returning to defaults Control/Restore Defaults but no change. I have also tried reinstalling V2.3.2 Firmware. No change
Any suggestions please?
