### ISSUE TITLE
Z-axis Motor Modules do not stop when reach bottom

### ISSUE THREAD

**Issue by SLainii** [ZONESTAR3D/Z8P#9]
Our new Z8PM4PRO printed one test print, result wasn't good so we started to calibrate the bed. When select "Catch Probe z-offset" machine starts but when Right motor hits to ZSW it clicks but motor won't stop until select something else from LCD. It keep going down and hits to bed and push it downs. Firmware is updated today, and set default. What can be wrong?

**Comment by ZONESTAR3D** [comment]
Hi Friend,
        Thanks for contacting us.From your message, it seems like the Z ENDSTOP is disconnected with the control board.Please following the guide to do once "electronics parts auto testing" (Refer to this link: https://github.com/ZONESTAR3D/Z8P/tree/main/Z8P_FAQ#electronics-parts-auto-testing) and check if the Z ENDSTOP work well.If it is confirmed that the Z ENDSTOP does not working properly, please check:
1. Refer to the wiring guide (https://github.com/ZONESTAR3D/Z8P/tree/main/Z8P-MK2/1-Installation_Guide#wiring) to check if the wires of the Z limit switch are properly connected.
2. Check if the wire is disconnected with the limit switch.
        
            
        
    
         
        
            
                        HallyCTOShenZhen ZONSTAR INNV. Tech. Co., ***@***.***
            
        
     
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        6/20/2023 02:59
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              [ZONESTAR3D/Z8P] Z-axis Motor Modules do not stop when reach bottom (Issue #9)
        
      
    
  

Our new Z8PM4PRO printed one test print, result wasn't good so we started to calibrate the bed. When select "Catch Probe z-offset" machine starts but when Right motor hits to ZSW it clicks but motor won't stop until select something else from LCD. It keep going down and hits to bed and push it downs. Firmware is updated today, and set default. What can be wrong?
